<?xml version="1.0"?>

<robot name="my_robot" xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro" />
	<xacro:include filename="$(find velodyne_description)/urdf/HDL-32E.urdf.xacro"/>


	<xacro:arg name="gpu" default="false"/>
  	<xacro:property name="gpu" value="$(arg gpu)" />


	<property name="base_width_x" value="0.5"/>
	<property name="base_width_y" value="0.3" />
	<property name="base_height" value="0.1"/>

	<property name="wheel_radius" value="0.1" />
	<property name="wheel_length" value="0.02" />

	<property name="cylinder_length" value="0.2" />

	<property name="hokuyo_size" value="0.05" />

	<property name="PI" value="3.141592" />

  <macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
              izz="${m*r*r/2}" /> 
  </macro>

	  <link name="base_footprint">
		<visual>
		    <origin xyz="0 0 0" rpy="0 0 0" />
		    <geometry>
		        <box size="0.001 0.001 0.001" />
		    </geometry>
		</visual>
	  </link>


	<joint name="base_footprint_joint" type="fixed">
		<origin xyz="0 0 ${wheel_radius + base_height/2}" rpy="0 0 0" />
		<parent link="base_footprint"/>
		<child link="base_link" />
	 </joint>
  <gazebo reference="base_footprint">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>


	<link name="base_link">
		<visual>
			<origin xyz="0 0 ${wheel_radius + base_height/2}" rpy="0 0 0" />
			<geometry>
				<box size="${base_width_x} ${base_width_y} ${base_height}" />
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 ${wheel_radius + base_height}" rpy="0 0 0" />
			<geometry>
				<box size="${base_width_x} ${base_width_y} ${base_height}" />
			</geometry>
		</collision>

		<inertial>
		  <origin xyz="0 0 0" rpy="0 0 0"/>
		  <mass value="1"/>
		  <inertia
		    ixx="1.0" ixy="0.0" ixz="0.0"
		    iyy="1.0" iyz="0.0"
		    izz="1.0"/>
		</inertial>
	</link>
 
	<gazebo reference="base_link" >
		<material>Gazebo/White</material>
	</gazebo>	
	
	<link name="bl_wheel">
		<visual>
			<origin xyz="0 0 0" rpy="${PI/2} 0 0 " />
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_radius}" />
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="${PI/2} 0 0 " />
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_radius}" />
			</geometry>
		</collision>

		<inertial>
      		<origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      		<mass value="1"/>
			<cylinder_inertia  m="1" r="${wheel_radius}" h="${wheel_length}" />
    	</inertial>
	</link>

	<gazebo reference="bl_wheel" >
		<material>Gazebo/Black</material>
	</gazebo>

	<joint name="bl_wheel_joint" type="continuous" >
		<origin xyz="${-base_width_x/2} ${base_width_y/2 + wheel_length} ${wheel_radius}" rpy="0 0 0" />
		<parent link="base_link" />
		<child link="bl_wheel" />
    <axis xyz="0 1 0" rpy="0  0" />
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
	</joint>

	<transmission name="bl_wheel_joint_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="bl_wheel_joint" />
		<actuator name="bl_wheel_joint_motor">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<link name="fl_wheel">
		<visual>
			<origin xyz="0 0 0" rpy="${PI/2} 0 0 " />
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_radius}" />
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="${PI/2} 0 0 " />
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_radius}" />
			</geometry>
		</collision>
		<inertial>
			<origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
			<mass value="1"/>
			<cylinder_inertia  m="1" r="${wheel_radius}" h="${wheel_length}" />
		</inertial>
	</link>

	<gazebo reference="fl_wheel" >
		<material>Gazebo/Black</material>
	</gazebo>

	<joint name="fl_wheel_joint" type="continuous" >
		<origin xyz="${base_width_x/2} ${base_width_y/2 + wheel_length} ${wheel_radius}" rpy="0 0 0" />
		<parent link="base_link" />
		<child link="fl_wheel" />
    <axis xyz="0 1 0" rpy="0  0" />
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
	</joint>

	<transmission name="fl_wheel_joint_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="fl_wheel_joint" />
		<actuator name="fl_wheel_joint_motor">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>



	<link name="br_wheel">
		<visual>
			<origin xyz="0 0 0" rpy="${PI/2} 0 0 " />
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_radius}" />
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="${PI/2} 0 0 " />
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_radius}" />
			</geometry>
		</collision>

		<inertial>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <mass value="1"/>
			<cylinder_inertia  m="1" r="${wheel_radius}" h="${wheel_length}" />
    </inertial>
	</link>

	<gazebo reference="br_wheel" >
		<material>Gazebo/Black</material>
	</gazebo>

	<joint name="br_wheel_joint" type="continuous" >
		<origin xyz="${-base_width_x/2} ${-base_width_y/2 - wheel_length} ${wheel_radius}" rpy="0 0 0" />
		<parent link="base_link" />
		<child link="br_wheel" />
    <axis xyz="0 1 0" rpy="0  0" />
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
	</joint>

	<transmission name="br_wheel_joint_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="br_wheel_joint" />
		<actuator name="br_wheel_joint_motor">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>



	<link name="fr_wheel">
		<visual>
			<origin xyz="0 0 0" rpy="${PI/2} 0 0 " />
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_radius}" />
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="${PI/2} 0 0 " />
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_radius}" />
			</geometry>
		</collision>

		<inertial>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <mass value="1"/>
			<cylinder_inertia  m="1" r="${wheel_radius}" h="${wheel_length}" />
    </inertial>
	</link>

	<gazebo reference="fr_wheel" >
		<material>Gazebo/Blue</material>
	</gazebo>

	<joint name="fr_wheel_joint" type="continuous" >
		<origin xyz="${base_width_x/2} ${-base_width_y/2 - wheel_length} ${wheel_radius}" rpy="0 0 0" />
		<parent link="base_link" />
		<child link="fr_wheel" />
    <axis xyz="0 1 0" rpy="0  0" />
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
	</joint>

	<transmission name="fr_wheel_joint_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="fr_wheel_joint" />
		<actuator name="fr_wheel_joint_motor">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>


  <!-- impport Velodyne VLP-16 model on top of my_robot base link -->

  <VLP-16 parent="base_link" name="velodyne" topic="/velodyne_points">
      <origin xyz="0 0 0.2" rpy="0 0 0" />
  </VLP-16>

  <gazebo>
	<plugin name="velodyne_control" filename="libvelodyne_plugin.so"/>
  </gazebo>
	
  <!--
  <HDL-32E parent="base_link" name="velodyne2" topic="/velodyne_points2" hz="10" samples="220" gpu="${gpu}">
    <origin xyz="0 0 0.2" rpy="0 0 0" />
  </HDL-32E> -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">

      <rosDebugLevel>Debug</rosDebugLevel>
      <publishWheelTF>false</publishWheelTF>
      <robotNamespace>/</robotNamespace>
      <publishTf>1</publishTf>
      <publishWheelJointState>false</publishWheelJointState>
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <leftJoint>bl_wheel_joint</leftJoint>
      <rightJoint>br_wheel_joint</rightJoint>
      <wheelSeparation>${base_width_y + 2*wheel_length}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <broadcastTF>1</broadcastTF>
      <wheelTorque>30</wheelTorque>
      <wheelAcceleration>1.8</wheelAcceleration>
      <commandTopic>cmd_vel</commandTopic>
      <odometryFrame>odom</odometryFrame> 
      <odometryTopic>odom</odometryTopic> 
      <robotBaseFrame>base_link</robotBaseFrame>
      <legacyMode>false</legacyMode>
      <odometrySource>world</odometrySource> 
      <publishTf>1</publishTf>

    </plugin>
  </gazebo> 
<!--
	<gazebo>
	  <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
		<updateRate>100.0</updateRate>
		<robotNamespace>/</robotNamespace>
		<leftFrontJoint>fl_wheel_joint</leftFrontJoint>
		<rightFrontJoint>fr_wheel_joint</rightFrontJoint>
		<leftRearJoint>bl_wheel_joint</leftRearJoint>
		<rightRearJoint>br_wheel_joint</rightRearJoint>
		<wheelSeparation>${base_width_y + 2*wheel_length}</wheelSeparation>
		<wheelDiameter>${2*wheel_radius}</wheelDiameter>
		<robotBaseFrame>base_link</robotBaseFrame>
		<torque>30</torque>
		<topicName>cmd_vel</topicName>
		<commandTopic>cmd_vel</commandTopic>
		<broadcastTF>false</broadcastTF>
	  </plugin>
	</gazebo>
-->


</robot>


