<?xml version="1.0"?>
<robot name="g500_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">




  <property name="deg_to_rad" value="0.01745329251994329577"/>

  <!-- Right gripper -->
  <property name="grasp_frame_len" value="0.02" />
  <property name="grasp_frame_width" value="0.02" />
  <property name="grasp_frame_height" value="0.02" />


   <xacro:macro name="inertial_matrix" params="mass">
      <inertial>
      	<mass value="${mass}" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="0.5" iyz="0.0" izz="1.0" />
      </inertial>
   </xacro:macro>

   <xacro:include filename="$(find mastering_ros_robot_description_pkg)/urdf/sensors/xtion_pro_live.urdf.xacro"/>


  <!-- base link is the body of the robot -->
<!--
  <link name="base_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
          <sphere radius="0.03"/>
      </geometry>
    </visual>
  </link>

  <joint name="baselink_to_base" type="revolute">
    <parent link="base_link"/>
    <child link="base"/>
    <axis xyz="1 0 0"/>
    <origin rpy="0.045 0 0" xyz="0.25 0 0"/>
    <limit effort="30.0" lower="-3.14" upper="3.14" velocity="0.025"/>
  </joint> -->

 <!--
  <link name="base">
    <visual>
      <origin rpy="0 0 0" xyz="0.0 0 0.0"/>
      <geometry>
        <mesh filename="package://g500_arm_description/meshes/robot/ECA/arm0.3ds" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="Grey">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="-0.2 0 0.0"/>
      <geometry>
        <box size="0.25 0.12 0.2" />
      </geometry>
    </collision>
  </link> -->

  <link name="base_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.25 0.12 0.2" />
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>
      <geometry>
        <box size="0.25 0.12 0.2" />
      </geometry>
    </collision>
	<xacro:inertial_matrix mass="1" />
  </link>


  <joint name="q1" type="revolute">
    <parent link="base_link"/>
    <child link="L0"/>
    <axis xyz="0 0 1"/>
    <origin rpy="0.0 0.0 0.0" xyz="${0.25/2} 0.0 0.0"/>
    <limit effort="300" lower="-0.43" upper="1.54" velocity="0.025"/>
  </joint>

	<transmission name="q1_joint_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="q1" >
			<hardwareInterface>PositionJointInterface</hardwareInterface>
		</joint>
    <actuator name="motor1">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
	</transmission> 

 <!-- 
  <link name="L0">
  	<visual>
      <origin xyz="0.0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://g500_arm_description/meshes/robot/ECA/arm1.3ds" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="LightGrey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.18 0 0" rpy="0 0 0"/>
		  <geometry>
				<box size="0.2 0.1 0.18" />
			</geometry>
		</collision>
   </link> -->

 <!-- JUST MAKING SURE EVERYTHING IS FINE -->
 
  <link name="L0">
  	<visual>
      <origin xyz="0.1 0 0" rpy="0 0 0"/>
      <geometry>
		<box size="0.2 0.1 0.18" />
      </geometry>
      <material name="LightGrey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.1 0 0" rpy="0 0 0"/>
	  <geometry>
			<box size="0.2 0.1 0.18" />
		</geometry>
	</collision>
	<xacro:inertial_matrix mass="1" />
   </link> 

  <joint name="q2" type="revolute">
    <parent link="L0"/>
    <child link="L1"/>
    <axis xyz="0 0 1"/>
    <origin rpy="-1.57 0.0 0.0" xyz="0.2 0.0 0.0"/>
    <limit effort="300" lower="-0.10" upper="1.45" velocity="0.025"/>
  </joint>

	<transmission name="q2_joint_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="q2" >
			<hardwareInterface>PositionJointInterface</hardwareInterface>
		</joint>
    <actuator name="motor2">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
	</transmission> -->
<!--
   <link name="L1">
    <visual>
      <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
      <geometry>
        <mesh filename="package://g500_arm_description/meshes/robot/ECA/arm2.3ds" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="Grey">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.2 0 0.0"/>
		<geometry>
      <box size="0.3 0.2 0.15" />
		</geometry>
	 </collision>
  </link> -->

	<!-- JUST MAKING SURE EVERYTHING IS FINE -->


   <link name="L1">
    <visual>
      <origin rpy="0 0 0" xyz="0.15 0.0 0.0"/>
      <geometry>
		 <box size="0.3 0.2 0.15" />
      </geometry>
      <material name="Grey">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.15 0 0.0"/>
		<geometry>
      		<box size="0.3 0.2 0.15" />
		</geometry>
	 </collision>
	<xacro:inertial_matrix mass="1" />
  </link>
 
  <joint name="q3" type="revolute">
    <parent link="L1"/>
    <child link="L2"/>
    <axis xyz="0 0 1"/>
    <origin rpy="0.0 0 0" xyz="0.3 0.0 0.0"/>
    <limit effort="300" lower="-1.22" upper="0.645" velocity="0.09"/>
  </joint>

	<transmission name="q3_joint_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="q3">
			<hardwareInterface>PositionJointInterface</hardwareInterface>
		</joint>
    <actuator name="motor3">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
	</transmission> 
<!--
  <link name="L2">
    <visual>
      <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
        <geometry>
          <mesh filename="package://g500_arm_description/meshes/robot/ECA/arm3.3ds" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.75 0.75 0.75 1.0"/>
        </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.15 0.08 0.12" />
      </geometry>
    </collision>
  </link> -->


	<!-- JUST MAKING SURE EVERYTHING IS FINE -->


  <link name="L2">
    <visual>
      <origin rpy="0 0 0" xyz="0.075 0.0 0.0"/>
        <geometry>
			<box size="0.15 0.08 0.12" />
        </geometry>
        <material name="LightGrey">
          <color rgba="0.75 0.75 0.75 1.0"/>
        </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.075 0.0 0.0"/>
      <geometry>
        <box size="0.15 0.08 0.12" />
      </geometry>
    </collision>
	<xacro:inertial_matrix mass="1" />
  </link>

  <joint name="q4" type="revolute">
    <parent link="L2"/>
    <child link="L3"/>
    <axis xyz="0 0 1"/>
    <origin rpy="1.57 0 0" xyz="0.15 0.0 0.0"/>
    <limit effort="300" lower="-3.12" upper="3.12" velocity="0.09"/>
  </joint>

	<transmission name="q4_joint_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="q4" >
			<hardwareInterface>PositionJointInterface</hardwareInterface>
		</joint>
    <actuator name="motor4">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
	</transmission> -->

<!--
  <link name="L3">
    <visual>
      <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
      <geometry>
        <mesh filename="package://g500_arm_description/meshes/robot/ECA/arm4.3ds" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="LightBlack">
        <color rgba="0.2 0.2 0.2 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.15"/>
      <geometry>
        <box size="0.12 0.2 0.28" />
      </geometry>
    </collision>
  </link> -->



  <link name="L3">
    <visual>
      <origin rpy="0 0 0" xyz="0.06 0.0 0.15"/>
      <geometry>
		   <box size="0.12 0.2 0.28" />
      </geometry>
      <material name="LightBlack">
        <color rgba="0.2 0.2 0.2 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.06 0 0.15"/>
      <geometry>
        <box size="0.12 0.2 0.28" />
      </geometry>
    </collision>
	<xacro:inertial_matrix mass="1" />
  </link>


     <link name="grasping_frame">

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.0001"/>
        <cuboid_inertia mass="0.0001" x="0.001" y="0.001" z="0.001"/>
        <inertia  ixx="1.0" ixy="0.0"  ixz="0.0"  iyy="100.0"  iyz="0.0"  izz="1.0" />

      </inertial>

    <visual>
      <origin xyz="0 0 0"/>
      <geometry>

          <box size="${grasp_frame_len} ${grasp_frame_width} ${grasp_frame_height}" />


      </geometry>
      <material name="White" />
    </visual>

    </link>

    <joint name="grasping_frame_joint" type="fixed">
      <parent link="L2"/>
      <child link="grasping_frame"/>
      <origin xyz="${grasp_frame_len/2 + 0.12 + 0.15} ${-0.15} 0" rpy="0 0 0"/>
    </joint>

    <xacro:xtion_pro_live name="rgbd_camera" parent="base">
    <origin xyz="0.1 0 1" rpy="0 ${75.0 * deg_to_rad} 0"/>
    <origin xyz="0 0 0" rpy="${-90.0 * deg_to_rad} 0 ${-90.0 * deg_to_rad}"/>
  </xacro:xtion_pro_live>

	<gazebo reference="gazebo_ros_control" plugin="libgazebo_ros_control.so" >
		<robotNameSpace>/g500_arm</robotNameSpace>
	</gazebo>
<!--
  <joint name="jaw" type="revolute">
    <parent link="L3"/>
    <child link="L4"/>
    <axis xyz="0 1 0"/>
    <origin rpy="0 0 0" xyz="0.0 0.0 0.328"/>
    <limit effort="30.0" lower="-3.14" upper="3.14" velocity="0.025"/>
  </joint>

  <link name="L4">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
          <sphere radius="0.03"/>
      </geometry>
    </visual>
  </link> -->

</robot>
